name: Pipeline de testes
on: 
  push: 
    branches: ["main", "tests"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'     
      - name: Install dependencies
        run: npm 
      - name: Run tests
        run: npm run test